name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install build tools
      run: sudo apt-get install -y flex bison
    - name: make (1)
      run: make
    - name: make (2)
      run: make -B
    - name: make (3)
      run: make -B
    - name: make test
      run: make test
